# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f773c8ba0e0bbbe07e1f19bfef8fbbeb33d5683317197a7a4e1f688a0091c74602aa876d4981d5203c868e1df8a8aa92ba55aba1c32a633771b1cffb4a3cc8d

test:
  secret_key_base: dd3b9ff51d22a8a0539ae0c36a91b0b772e9c6caddd42a3705558a0960eeb008cd0922937497e95f1ccfd86d38882eac8ce77cedd32a3d8fdee8603da324ba63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
